# FIXME This comes from the ootao xdi lib. don't duplicate

module AtLinksafe
module XdiStatus

  SUCCESS = '100'
  BAD_REPLACE_CONTEXT = '200'
  BAD_XML_CONTEXT = '201'
  BAD_GRAPH_LEVEL = '202'
  UNKNOWN_SYNONYM = '203'
  NON_UNIQUE_SYNONYM = '204'
  INVALID_SYNONYM = '205'
  NON_UNIQUE_REFERENCE = '206'
  BAD_TARGET_XRI = '207'
  MALFORMED_XMLSTRING = '208'
  OPERATION_NOT_PERMISSIONED = '209'
  SIGNED_CONTRACT_EXPECTED = '210'
  BAD_MODE = '211'
  CANNOT_FORWARD_PROXIED_REQUEST = '212'
  INVALID_SESSION = '213'
  EXPIRED_SESSION = '214'
  SYSTEM_EXCEPTION = '300'
  CODE_320 = '320'

end
end
